Skip test_with_specific_ruby on Xcode 15

diff --git a/e2e/bitrise.yml b/e2e/bitrise.yml
--- a/e2e/bitrise.yml
+++ b/e2e/bitrise.yml
@@ -50,6 +50,26 @@ workflows:
     - _check_cache_include_paths
 
   test_with_specific_ruby:
+    steps:
+    - script:
+        inputs:
+        - content: |-
+            #!/bin/env bash
+            set -e
+            if [[ ${XCODE_MAJOR_VERSION} -eq 15 ]]; then
+              echo "This test case is temporarily skipped on Xcode 15..."
+              exit 0
+            fi
+            envman add --key XCODE_MAJOR_VERSION_IS_NOT_15 --value "true"
+    - script:
+        run_if: '{{enveq "XCODE_MAJOR_VERSION_IS_NOT_15" "true"}}'
+        inputs:
+        - content: |-
+            #!/bin/env bash
+            set -x # Do not set -e as bitrise command is expected to fail
+            bitrise run --config=./e2e/bitrise.yml utility_test_with_specific_ruby
+
+  utility_test_with_specific_ruby:
     envs:
     - TEST_APP_URL: https://github.com/bitrise-io/Bitrise-iOS-Cocoapods-Sample.git
     - TEST_APP_BRANCH: main
